from .patient_resource import PatientResource
from .doctor_resource import DoctorResource
from .alert_resource import AlertResource
from .teleconsultation_resource import TeleconsultationResource
from .health_record_resource import HealthRecordResource
from .doctorLogin import DoctorLogin
from .doctorRegistration import DoctorRegistration
from .patientLogin import PatientLogin
from .patientRegistration import PatientRegistration
from .recorded_data import RecordedDataResource
from .latest_record import LatestRecord
from .get_aval_time_slots import GetAvailTimeSlot
from .send_sos import SendSOS
